<?php 
define("APP_Path","http://dev.letsintern.com");
define("APP_WebPath","../LI.Web/");
define("Student_Web_Path","../LI.Web/Student/");
define("Employer_Web_Path","../LI.Web/Employer/");
define("Business_Path","../../LI.BusinessManagement/");
define("Entity_Path","../../LI.Entities/");
define("Utility_Path","../../Utilities/");
define("Data_Path","../../LI.DataAccessManagement/");
define("Adapter_Path","../../LI.DataAccessManagement/MySqlDataAdapter/");
define("ParentPath","../");
?>